version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: rocker/tidyverse
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:3b:e8:1d:9a:32:6f:ca:ca:9e:f1:ce:e2:8a:e8:03"
      - checkout
      - restore_cache:
          keys:
            - cache2
      - run:
          command: |
            sudo apt-get update -y
            sudo apt-get install -y curl python3-pip python3-venv ssh-client ssh git
            pip3 install virtualenv
      - run:
          name: Keyscan Github (HACK)
          command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          command: |
            sudo apt-get install -y pandoc libudunits2-dev libgdal-dev libxt-dev libglu1-mesa-dev
            sudo R -e 'install.packages(c("devtools", "mvtnorm")); devtools::install_github("hypertidy/anglr"); devtools::install_github("johannesbjork/LaCroixColoR"); devtools::install_deps(dependencies = TRUE) '
      - save_cache:
          key: cache2
          paths:
            - "/usr/local/lib/R/site-library"
      - store_artifacts:
          path: man/
          destination: man
      - run:
          command: |
            rm -rf build
            mkdir build
            mkdir build/ggplot2
            mkdir build/r
            for i in r/*.Rmd; do Rscript -e "rmarkdown::render('$i', output_dir='build/r')"; done
            for i in ggplot2/*.Rmd; do Rscript -e "rmarkdown::render('$i', output_dir='build/ggplot2')"; done
            python3 -m venv venv
            . venv/bin/activate
            pip3 install python-frontmatter
            curl https://raw.githubusercontent.com/plotly/documentation/source-design-merge/front-matter-ci.py > front-matter-ci.py
            python front-matter-ci.py build/r
            curl https://raw.githubusercontent.com/plotly/documentation/source-design-merge/check-or-enforce-order.py > check-or-enforce-order.py
            python check-or-enforce-order.py build/r
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd build
              git init
              git config user.name joedamiba
              git config user.email joseph.damiba@plot.ly
              rm -rf r/*.html
              sed -i.bkp 's/<!--.*-->//g' r/*md && rm r/*.bkp
              rm -rf ggplot2/*.html
              sed -i.bkp 's/<!--.*-->//g' ggplot2/*md && rm ggplot2/*.bkp
              git add *
              git commit -m build
              git push --force git@github.com:plotly/plotly.r-docs.git master:built
              rm -rf .git
            fi
