version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "32:3b:e8:1d:9a:32:6f:ca:ca:9e:f1:ce:e2:8a:e8:03"
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          command: |
            apt-get update -y
            apt-get install -y pandoc
      - run:
          command: |
            Rscript -e 'rmarkdown::render("r/2015-07-30-bar-charts.Rmd")'
      - run: 
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git init
              git config user.name joedamiba
              git config user.email joseph.damiba@plot.ly
              rm -rf *.html
              git add *
              git commit -m build
              git push --force git@github.com:plotly/plotly.r-docs.git master:built
              rm -rf .git
            fi
