version: 2
jobs:
  build:
    docker:
      - image: appsilon/ci-base:1.0
    steps:
      - checkout
      - run:
          command: |
            Rscript -e RdepLibs.R
      - run:
          command: |
            Rscript -e 'rmarkdown::render("r/2015-07-30-bar-charts.Rmd")
      - store_artifacts:
          path: man/
          destination: man